### ISSUE TITLE
nvda 2022.1? compatibility

### ISSUE THREAD

**Issue by mjonsson1986** [nvdaaddons/instantTranslate#10]
will this addon soon support latest nvda 2022?

**Comment by DraganRatkovich** [comment]
@mhameed @tspivey @beqabeqa473 @leonardder @ABuffEr Do you have any plans to support this add-on for the 2022 version of NVDA?

**Comment by ABuffEr** [comment]
Hi,
I don't work on this add-on from a lot of time, but using alpha versions from weeks it seems there is no particular issues to be fixed for 2022.1. So the question is just who have to release the new version. I wait the replies by others.

**Comment by nvdaes** [comment]
Hi Alberto: since other people aren"t providing releases for this useful addon, I would ask you to do it if you can. 😀

**Comment by DraganRatkovich** [comment]
Absolutely agree with @nvdaes If it suits you @ABuffEr you can bump the version and compatibility.

**Comment by mhameed** [comment]
@ABuffEr congratulations, you are the new maintainer :-)

I dont use windows so can't test, so I am the wrong person to do it.

Thanks.

**Comment by nvdaes** [comment]
Happy to see you here Mesar!
Also, @ABuffEr , in case you need my help, as a user of this add-on, let me know, though I know you can work better than me. But just in case I'm here.

**Comment by beqabeqa473** [comment]
Hello.

I planned to release an update when 2022 would be released.

On 5/17/22, Noelia Ruiz Martínez ***@***.***> wrote:
> Happy to see you here Mesar!
> Also, @ABuffEr , in case you need my help, as a user of this add-on, let me
> know, though I know you can work better than me. But just in case I'm here.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/nvdaaddons/instantTranslate/issues/10#issuecomment-1128718728
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by ABuffEr** [comment]
@beqabeqa473 , perfect! I was waiting your reply, you are the last person worked on this add-on, so it sounds right to me :) And I have some problems with syncing forks, apparently.
