### ISSUE TITLE
Settings changes won't sync with profile configs

### ISSUE THREAD

**Issue by Yeldece** [nvdaaddons/instantTranslate#12]
When you swap your language preferences, or set a new language from the options page, the new selection won't saved on current active profile (if exist). But rather it saves and uses them globaly all the time.

**steps to produce**
1. Create multiple profiles:
2. Set source and target language from settings panel
3.  Activate a profile
4. Repeat 2 with two new languages.
5. Check, Your main settings also changed.

I will create a pull request to show how I fixed it, but it is probably a very bad way of solving this problem. So please track if there's anything wrong with nvda unless this is a new feature, even so let's add it as a personaliozed feature  and let users select if they wanna use settings globaly or not.

**Comment by beqabeqa473** [comment]
superseeded by #beqabeqa473/instantTranslate/issues/20
