### ISSUE TITLE
nvda 2021 compatibility?

### ISSUE THREAD

**Issue by mjonsson1986** [nvdaaddons/instantTranslate#6]
any plan to do the addon compatible with latest nvda 2021 beta?

**Comment by CyrilleB79** [comment]
@mjonsson1986 even being a fork, the real active repo for Instant Translate add-on is [this one](https://github.com/beqabeqa473/instantTranslate) in @beqabeqa473's account.

In this repo, you will see that 2021.1 compatibility is already implemented (in stable branch) even if no release has been done yet.
@beqabeqa473 is a release planned soon for direct download (and also to update download link on the comunity website)?

**Comment by beqabeqa473** [comment]
Hello.

yes, i need to finally sort out things with branches nad make a release;

i will try to do on these weekends.

On 6/18/21, Cyrille Bougot ***@***.***> wrote:
> @mjonsson1986 even being a fork, the real active repo for Instant Translate
> add-on is [this one](https://github.com/beqabeqa473/instantTranslate) in
> @beqabeqa473's account.
>
> In this repo, you will see that 2021.1 compatibility is already implemented
> (in stable branch) even if no release has been done yet.
> @beqabeqa473 is a release planned soon for direct download (and also to
> update download link on the comunity website)?
>
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvdaaddons/instantTranslate/issues/6#issuecomment-863957982


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili
